import os
from openai import OpenAI

api_key = os.getenv("OPENAI_API_KEY")
if not api_key:
    raise ValueError("OPENAI_API_KEY is not set")

client = OpenAI(api_key=api_key)

training_data_path = "autogenerated_training_data.jsonl" 

if not os.path.exists(training_data_path):
    raise FileNotFoundError(f"Training data file '{training_data_path}' not found")

with open(training_data_path, "rb") as f:
    file_response = client.files.create(
        file=f,
        purpose="fine-tune"
    )

fine_tune_response = client.fine_tuning.jobs.create(
    training_file=file_response.id,
    model="gpt-3.5-turbo"
)
